config/routes.rb
Chanson::Application.routes.draw do
  resources :subjects do
  resources :pages
end
  resources :pages do
  resources :sections
  end
    resources :users do
    member do
      get :following, :followers
    end
  end
   resources :sessions, only: [:new, :create, :destroy]
   resources :microposts, only: [:create, :destroy]
   resources :relationships, only: [:create, :destroy]
      root  'static_pages#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

 
  match '/content', to: 'static_pages#show', via: 'get'
  match '/home',  to: 'static_pages#home', via: 'get'
 match '/show',  to: 'static_pages#picture', via: 'get'
 
  
 match '/admin', to: 'sessions#menu',        via: 'get'

  

end

app/models/section.rb
class Section < ActiveRecord::Base
	belongs_to :page
	validates :page_id, presence: true
	validates :name,  presence: true, length: { maximum: 255 }
	
	
	CONTENT_TYPES = ['text', 'HTML']
	 validates :content_type, inclusion: { in: CONTENT_TYPES, message: "must be one of: #{CONTENT_TYPES.join(', ')}"}
	 validates :content, presence: true
	scope :visible, -> {where(visible: 'true') }
   	scope :invisible, -> {where(visible: 'false') }
 
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :signed_in_user	
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :find_page

  # GET /sections
  # GET /sections.json
  def index
    @sections = @page.sections.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = @page.sections.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = @page.sections.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to [@page, @section], notice: 'Section was successfully created.' }
        format.json { render action: 'show', status: :created, location: @section }
      else
        format.html { render action: 'new' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to [@page, @section], notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to page_path(@page) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name, :position, :visible, :content_type, :content, :page_id)
    end
    def find_page
    if params[:page_id]
      @page = Page.find_by_id(params[:page_id])
    end
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for([@page, @section]) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div><%= f.hidden_field :page_id %></div>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.radio_button(:content_type, 'text') %> Text
      <%= f.radio_button(:content_type, 'HTML') %> HTML
    
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing section</h1>
<h3><%= link_to 'Back to page', page_path(@page) %></h3>


<%= render 'form' %>

app/views/sections/index.html.erb
<% if current_user.admin?  %>
<h1>Listing sections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Visible</th>
      <th>Content type</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name %></td>
        <td><%= section.position %></td>
        <td><%= section.visible %></td>
        <td><%= section.content_type %></td>
        <td><%= section.content %></td>
        <td><%= link_to 'Show', page_section_path(@page, section) %></td>
        <td><%= link_to 'Edit', edit_page_section_path(@page, section) %></td>
        <td><%= link_to 'Destroy', [@page, section], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_page_section_path(@page) %>
<% end %>

app/views/sections/new.html.erb
<h1>New section</h1>
<h3><%= link_to 'Back to page', page_path(@page) %></h3>

<%= render 'form' %>

<h3><%= link_to 'Back to page', page_path(@page) %></h3>

app/views/sections/show.html.erb
<h3><%= link_to 'Back to page', page_path(@page) %> |  <%= link_to 'Edit section', edit_page_section_path(@page, @section) %></h3>
<p id="notice"><%= notice %></p>

<p>
  <strong>Sections Name:</strong>
  
   <%=  @section.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @section.position %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @section.visible %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @section.content_type %>
</p>

<p>
  <strong>Content:</strong>
  
  <%=  @section.content %>
</p>
<h3><%= link_to 'Destroy', [@page, @section], method: :delete, data: { confirm: 'Are you sure?' } %></h3>