config/routes.rb
Chanson::Application.routes.draw do
  resources :subjects do
  resources :pages
end
  resources :pages do
  resources :sections
  end
    resources :users do
    member do
      get :following, :followers
    end
  end
   resources :sessions, only: [:new, :create, :destroy]
   resources :microposts, only: [:create, :destroy]
   resources :relationships, only: [:create, :destroy]
      root  'static_pages#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

 
  match '/content', to: 'static_pages#show', via: 'get'
  match '/home',  to: 'static_pages#home', via: 'get'
 match '/show',  to: 'static_pages#picture', via: 'get'
 
  
 match '/admin', to: 'sessions#menu',        via: 'get'

  

end

app/views/pages/_form.html.erb
<%= form_for([@subject, @page]) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div><%= f.hidden_field :subject_id %></div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br>
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<li>
  <span class="name"><%= page.name %></span>
  
</li>

app/views/pages/edit.html.erb
<h1>Editing page</h1>
<h3><%= link_to 'Back to subject', subject_path(@subject) %> | <%= link_to 'Show page content', subject_page_path(@subject, @page) %> 
</h3>

<%= render 'form' %>

app/views/pages/index.html.erb
<% if current_user.admin?  %>
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Permalink</th>
      <th>Position</th>
      <th>Visible</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.name %></td>
        <td><%= page.permalink %></td>
        <td><%= page.position %></td>
        <td><%= page.visible %></td>
        <td><%= link_to 'Show', subject_page_path(@subject, page)%></td>
        <td><%= link_to 'Edit', edit_subject_page_path(@subject, page) %></td>
        <td><%= link_to 'Destroy', [@subject, page], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_subject_page_path(@subject) %>
<% end %>

app/views/pages/new.html.erb
<h3>New page</h3>
<h3><%= link_to 'Back to subject', subject_path(@subject) %></h3>


<h1><%= @subject.name %></h1>
      
<%= render 'form' %>

app/views/pages/show.html.erb
<h3><%= link_to 'Back to subject', subject_path(@subject) %> <td><%= link_to 'Destroy', [@subject, @page], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr></h3>

<p id="notice"><%= notice %></p>

<h1>
  <strong>Page name:</strong>
  <%= @page.name %>
</h1>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<p>
  <strong>Position:</strong>
  <%= @page.position %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @page.visible %>
</p>
<% if @page.sections.any? %>
      <p>Sections (<%= @page.sections.count %>)</p>
      <%  @page.sections.each do |section| %> 
     <h2><%= section.name %><p><%= link_to 'Show sections content' , page_section_path(@page, section)%></p></h2>
     <% end %>
     <% else %>
     <p><%= 'There is no any section' %></p>
	 <% end %>
 
<h3><%= link_to 'new section', new_page_section_path(@page) %></h3>