config/routes.rb
Chanson::Application.routes.draw do
  resources :subjects do
  resources :pages
end
  resources :pages do
  resources :sections
  end
    resources :users do
    member do
      get :following, :followers
    end
  end
   resources :sessions, only: [:new, :create, :destroy]
   resources :microposts, only: [:create, :destroy]
   resources :relationships, only: [:create, :destroy]
      root  'static_pages#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

 
  match '/content', to: 'static_pages#show', via: 'get'
  match '/home',  to: 'static_pages#home', via: 'get'
 match '/show',  to: 'static_pages#picture', via: 'get'
 
  
 match '/admin', to: 'sessions#menu',        via: 'get'

  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :pages
	 accepts_nested_attributes_for :pages, allow_destroy: true
	 
	  validates :name,  presence: true, length: { maximum: 50 }
	 scope :visible, -> {where(visible: 'true') }
   	scope :invisible, -> {where(visible: 'false') }
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :signed_in_user
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  	# @page = Page.new
  #	@pages = @subject.pages
  #	@nouvon = @subject.pages.build(:permalink => 'ce et moi')
  #	if !@nouvon.save

   #   render 'static_pages/home'
    # end
  
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subject }
      else
        format.html { render action: 'new' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :position, :visible)
    end
    
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
   <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<li>
  <span class="name"><%= subject.name %></span>
  
</li><li>
      <tr>
        <td>attention!<%= link_to subject.name, subject %></td>
        <td><%= subject.position %></td>
        <td><%= subject.visible %></td>
        <td class="center"><%= subject.pages.size %></td>
    
         attention!<%= link_to subject.name, subject %>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
</li>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>
<h3> <%= link_to 'Back to Subject list', subjects_path %></h3>
<%= render 'form' %>

app/views/subjects/index.html.erb
<% if current_user.admin?  %>
  
<h1>Listing subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Visible</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.position %></td>
        <td><%= subject.visible %></td>
        
        
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3><%= link_to 'New Subject', new_subject_path %><h3>
<% end %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= link_to 'Back to subject list', subjects_path %></h3>
<p>
  <strong>Subjects Name:</strong>
  <h1> <%= @subject.name %></h1>
</p>

 <% if @subject.pages.any? %>
      <p>Subject involve the next pages (<%= @subject.pages.count %>)</p>
      <%  @subject.pages.each do |page| %> 
     <h2><%= page.name %><p><%= link_to 'Edit page name' , edit_subject_page_path(@subject, page)%> | <%= link_to 'Show page content' , subject_page_path(@subject, page)%></p></h2>
     <% end %>
     <% else %>
     <p><%= 'There is no any pages' %></p>
   
     

 <% end %>
	
 
<h3><%= link_to 'new page', new_subject_page_path(@subject) %> </h3>