config/routes.rb
Chanson::Application.routes.draw do
  resources :subjects do
  resources :pages
end
  resources :pages do
  resources :sections
  end
    resources :users do
    member do
      get :following, :followers
    end
  end
   resources :sessions, only: [:new, :create, :destroy]
   resources :microposts, only: [:create, :destroy]
   resources :relationships, only: [:create, :destroy]
      root  'static_pages#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

 
  match '/content', to: 'static_pages#show', via: 'get'
  match '/home',  to: 'static_pages#home', via: 'get'
 match '/show',  to: 'static_pages#picture', via: 'get'
 
  
 match '/admin', to: 'sessions#menu',        via: 'get'

  

end

app/views/layouts/_aside_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
  <div  class="navbar-header">
  
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
   
    <%= link_to "Galina Ridna", root_path, id: "name", :class => "navbar-brand" %>
     
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
  
    <ul class="nav navbar-nav hidden-lg hidden-md">
      
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages about art <b class="caret"></b></a>
        <ul class="dropdown-menu">
          
          <% if @feed_subjects.any? %>
 
       <%= render partial: 'shared/feed_subject', collection: @feed_subjects %>
            <% end %>
        </ul>
      </li>
    </ul>
    
    
    
    <ul class="nav navbar-nav navbar-right">
     <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About project", home_path %></li>
           <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
        <ul class="dropdown-menu">
        <li><%= link_to "Profile", admin_path %></li>          
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <% if current_user.admin? %>
         <li><%= link_to "Contenu de Chanson", subjects_path %></li>
              <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
        </ul>
      </li>
      <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
 </div>
</nav>

app/views/layouts/_footer.html.erb
<footer class="footer">
 <nav>
    <a><%= image_tag("pict4.png", alt: "Imaginasion") %>Et la vie continue</a>
    aujourd'hui
    <ul>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to image_tag("pict3.png", alt: "Imaginasion"), '#' %>
     <p class="center">&copy; 2013 - Chanson</p></li>  
    </ul>
  </nav>
</footer>

app/views/layouts/_footer_st_pages.html.erb
<footer class="footer">
  <nav>
  
     <ul>
     <li><%= link_to image_tag("pict3.png", alt: "Imaginasion"), '#' %>
     <p class="center clear">&copy; 2013-2014 Chanson</p></li>  
    </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
  <div  class="navbar-header">
  
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
   
    <%= link_to "Galina Ridna", root_path, id: "name", :class => "navbar-brand" %>
    
     
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    
    
    <ul class="nav navbar-nav navbar-right">
     <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About project", home_path %></li>
           <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", admin_path %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <% if current_user.admin? %>
         <li><%= link_to "Contenu de Chanson", subjects_path %></li>
              <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
        </ul>
      </li>
      <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
 </div>
</nav>
  </div>
</header>

app/views/layouts/_navigation.html.erb
<% if @feed_subjects.any? %>
  <class="menu">
    <%= render partial: 'shared/feed_subject', collection: @feed_subjects %>
  <% end %>
<div class="line"><%= image_tag("pict6.png", alt: "Imaginasion") %><a>email@galinaridna.com</a></div>
   

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
     <% flash.each do |key, value| %>
       <%= content_tag(:div, value, class: "alert alert-#{key}") %>
         <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
</head>
<body>
 <%= render 'layouts/aside_header' %>
<div class="container" >
 
    <div id="main">
    <div class="row">
    <div class="col-md-3 hidden-xs hidden-sm">

  
      <div id="navigation">     
      <%= render 'layouts/navigation' %>
      </div> 
     </div><!--  col-md-3 -->
 
 
<div class="col-xs-12 col-sm-12 col-md-9">
    
      <% flash.each do |key, value| %>
         <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <div id="content">
        <%= yield %>
      </div>
     </div><!--  .col-xs-1 .col-md-9 -->
     </div> <!-- row -->  
    </div><!-- main --> 
   
  <%= render 'layouts/footer_st_pages' %> 
  <%= debug(params) if Rails.env.development? %> 
  </div><!-- container -->

</body>
</html>
